export interface ContentItem {
  basvuruNo?: number;
  sonDegisiklikZamani?: string;
  olusturulmaZamani?: string;
  basvuruTarihi?: string;
  basvuruKararTarihi?: string;
  reddeItirazKararTarihi?: string | null;
  reddeItirazTarihi?: string | null;
  basvuruTuru?: string;
  basvuruTipi?: string;
  uzatmaBasvurusununYapildigiBasvuruNo?: number | null;
  talepEdilenIzinBaslangicTarihi?: string;
  talepEdilenIzinBitisTarihi?: string;
  retAciklamasi?: string | null;
  serhler?: string | null;
  islemAciklamasi?: string;
  islemTipi?: string;
  islemTarihi?: string;
  aylikBrutUcret?: number;
  paraBirimi?: string;
  meslekTanim?: string;
  meslekIskurKodu?: string;
  isvereniVarMi?: boolean;
  isyeriSgkTescilNumarasi?: string | null;
  isyeriIl?: string | null;
  isyeriIlce?: string | null;
  isyeriIlceKodu?: number | null;
  isyeriMeskenId?: number | null;
  isyeriAdresi?: string;
  isyeriUnvan?: string;
  isyeriNaceKodu?: string;
  isyeriSermayeYapisi?: string | null;
  isyeriFirmaTipi?: string;
  isyeriVergiNumarasi?: string | null;
  calisacagiIl?: string;
  calisacagiIlKodu?: number;
  calisacagiIlce?: string;
  calisacagiIlceKodu?: number;
  calisacagiMeskenId?: string;
  calisacagiAdres?: string | null;
  onayVerilenBaslangicTarihi?: string;
  onayVerilenBitisTarihi?: string;
  aktiflesmeTarihi?: string;
  onayTebligTarihi?: string;
  iptalSonlandirmaTarihi?: string;
  iptalSonlandirmaGerekcesi?: string;
  izinVerilenIl?: string;
  izinAktifMi?: boolean;
  izinDurumu?: string;
  calismaIzniTuru?: string;
  adi?: string;
  soyadi?: string;
  babaAdi?: string;
  anaAdi?: string;
  cinsiyeti?: string;
  dogumYeri?: string;
  dogumYeriKodu?: number;
  dogumTarihi?: string;
  medeniHali?: string;
  ikametIlKodu?: number | null;
  ikametIl?: string | null;
  ikametVerilisAmaci?: string | null;
  uyruk?: string;
  uyrukKodu?: number;
  uyrukDiger?: string | null;
  esininAdi?: string;
  esininSoyadi?: string;
  esTckn?: string | null;
  geciciKorumaStatusu?: string;
  esUyruk?: string;
  esUyrukKodu?: number;
  eposta?: string;
  eposta2?: string | null;
  telefon?: string;
  telefon2?: string | null;
  telefonKodu?: string | null;
  telefon2Kodu?: string | null;
  adres?: string | null;
  disIsleriReferansNumarasi?: string;
  yabanciKimlikNumarasi?: string;
  pasaportNumarasi?: string;
  pasaportSonGecerlilikTarihi?: string;
  passportType?: string;
  anadil?: string;
  bilinenDiller?: string;
  turkceSeviyesi?: string;
  egitimSeviyesi?: string;
  liseOkul?: string;
  universiteOkul?: string | null;
  universiteBolum?: string | null;
  universiteBaslangicTarihi?: string | null;
  universiteMezuniyetTarihi?: string | null;
  yuksekogretimOkul?: string | null;
  yuksekogretimBolum?: string | null;
  yuksekogretimBaslangicTarihi?: string | null;
  yuksekogretimMezuniyetTarihi?: string | null;
}

export interface DataContent {
  content: ContentItem[];
}

export interface ApiResponseType {
  success: boolean;
  message: string;
  data: DataContent;
}
