import { ContentItem } from "@/app/types/data-types/dataTypes";

export const dummyData: ContentItem[] = [
  {
    basvuruNo: 123456,
    yabanciKimlikNumarasi: "YKN123456789",
    izinAktifMi: true,
    izinDurumu: "Onaylandı",
    basvuruTuru: "Çalışma İzni",
    basvuruTipi: "İlk Başvuru",
    calismaIzniTuru: "Süreli",
    adi: "Ali",
    soyadi: "Yılmaz",
    izinVerilenIl: "Ankara",
    basvuruTarihi: "2024-01-01T17:19:49.341+03:00",
    basvuruKararTarihi: "2025-01-05",
    onayVerilenBaslangicTarihi: "2025-01-10",
    onayVerilenBitisTarihi: "2026-01-10",
    aktiflesmeTarihi: "2025-01-15",
    onayTebligTarihi: "2025-01-12",
    iptalSonlandirmaTarihi: null,
    iptalSonlandirmaGerekcesi: null,
    sonDegisiklikZamani: "2025-01-12T12:30:00",
    olusturulmaZamani: "2025-01-01T10:00:00",
    reddeItirazKararTarihi: null,
    reddeItirazTarihi: null,
    uzatmaBasvurusununYapildigiBasvuruNo: null,
    talepEdilenIzinBaslangicTarihi: "2025-01-10",
    talepEdilenIzinBitisTarihi: "2026-01-10",
    retAciklamasi: null,
    serhler: null,
    islemAciklamasi: "Başvuru Onaylandı",
    islemTipi: "Onay",
    islemTarihi: "2025-01-05",
    aylikBrutUcret: 15000,
    paraBirimi: "TRY",
    meslekTanim: "Mühendis",
    meslekIskurKodu: "1234",
    isvereniVarMi: true,
    isyeriSgkTescilNumarasi: "SGK123456",
    isyeriIl: "İstanbul",
    isyeriIlce: "Kadıköy",
    isyeriIlceKodu: 34,
    isyeriMeskenId: 1001,
    isyeriAdresi: "Bağdat Caddesi No:123",
    isyeriUnvan: "ABC Teknoloji A.Ş.",
    isyeriNaceKodu: "6201",
    isyeriSermayeYapisi: "Özel",
    isyeriFirmaTipi: "Anonim Şirket",
    isyeriVergiNumarasi: "V123456789",
    calisacagiIl: "Ankara",
    calisacagiIlKodu: 6,
    calisacagiIlce: "Çankaya",
    calisacagiIlceKodu: 6,
    calisacagiMeskenId: "2001",
    calisacagiAdres: "Kızılay Mah. Atatürk Bulv. No:456",
    babaAdi: "Mehmet",
    anaAdi: "Ayşe",
    cinsiyeti: "Erkek",
    dogumYeri: "Ankara",
    dogumYeriKodu: 6,
    dogumTarihi: "1990-05-15",
    medeniHali: "Evli",
    ikametIlKodu: 6,
    ikametIl: "Ankara",
    ikametVerilisAmaci: "Çalışma İzni",
    uyruk: "Türkiye",
    uyrukKodu: 90,
    uyrukDiger: null,
    esininAdi: "Fatma",
    esininSoyadi: "Yılmaz",
    esTckn: "12345678901",
    geciciKorumaStatusu: null,
    esUyruk: "Türkiye",
    esUyrukKodu: 90,
    eposta: "ali.yilmaz@example.com",
    eposta2: null,
    telefon: "+905555555555",
    telefon2: "+905555555556",
    telefonKodu: "+90",
    telefon2Kodu: "+90",
    adres: "Kızılay Mah. Ankara",
    disIsleriReferansNumarasi: "D123456789",
    pasaportNumarasi: "P12345678",
    pasaportSonGecerlilikTarihi: "2030-01-01",
    passportType: "Normal",
    anadil: "Türkçe",
    bilinenDiller: "İngilizce, Almanca",
    turkceSeviyesi: "Anadil",
    egitimSeviyesi: "Lisans",
    liseOkul: "Ankara Lisesi",
    universiteOkul: "ODTÜ",
    universiteBolum: "Bilgisayar Mühendisliği",
    universiteBaslangicTarihi: "2008-09-01",
    universiteMezuniyetTarihi: "2012-06-30",
    yuksekogretimOkul: null,
    yuksekogretimBolum: null,
    yuksekogretimBaslangicTarihi: null,
  },
  // New Dummy Data Entries
  {
    basvuruNo: 123457,
    yabanciKimlikNumarasi: "YKN123456790",
    izinAktifMi: true,
    izinDurumu: "Onaylandı",
    basvuruTuru: "Çalışma İzni",
    basvuruTipi: "İlk Başvuru",
    calismaIzniTuru: "Süreli",
    adi: "Ayşe",
    soyadi: "Demir",
    izinVerilenIl: "İstanbul",
    basvuruTarihi: "2025-02-01T17:19:49.341+03:00",
    basvuruKararTarihi: "2025-02-05",
    onayVerilenBaslangicTarihi: "2025-02-10",
    onayVerilenBitisTarihi: "2026-02-10",
    aktiflesmeTarihi: "2025-02-15",
    onayTebligTarihi: "2025-02-12",
    iptalSonlandirmaTarihi: null,
    iptalSonlandirmaGerekcesi: null,
    sonDegisiklikZamani: "2025-02-12T12:30:00",
    olusturulmaZamani: "2025-02-01T10:00:00",
    reddeItirazKararTarihi: null,
    reddeItirazTarihi: null,
    uzatmaBasvurusununYapildigiBasvuruNo: null,
    talepEdilenIzinBaslangicTarihi: "2025-02-10",
    talepEdilenIzinBitisTarihi: "2026-02-10",
    retAciklamasi: null,
    serhler: null,
    islemAciklamasi: "Başvuru Onaylandı",
    islemTipi: "Onay",
    islemTarihi: "2025-02-05",
    aylikBrutUcret: 16000,
    paraBirimi: "TRY",
    meslekTanim: "Doktor",
    meslekIskurKodu: "5678",
    isvereniVarMi: true,
    isyeriSgkTescilNumarasi: "SGK123457",
    isyeriIl: "Ankara",
    isyeriIlce: "Çankaya",
    isyeriIlceKodu: 6,
    isyeriMeskenId: 1002,
    isyeriAdresi: "Atatürk Bulvarı No:45",
    isyeriUnvan: "XYZ Sağlık A.Ş.",
    isyeriNaceKodu: "8610",
    isyeriSermayeYapisi: "Özel",
    isyeriFirmaTipi: "Anonim Şirket",
    isyeriVergiNumarasi: "V123456790",
    calisacagiIl: "İstanbul",
    calisacagiIlKodu: 34,
    calisacagiIlce: "Kadıköy",
    calisacagiIlceKodu: 34,
    calisacagiMeskenId: "2002",
    calisacagiAdres: "Bağdat Caddesi No:456",
    babaAdi: "Hasan",
    anaAdi: "Fatma",
    cinsiyeti: "Kadın",
    dogumYeri: "İstanbul",
    dogumYeriKodu: 34,
    dogumTarihi: "1992-06-15",
    medeniHali: "Bekar",
    ikametIlKodu: 34,
    ikametIl: "İstanbul",
    ikametVerilisAmaci: "Çalışma İzni",
    uyruk: "Türkiye",
    uyrukKodu: 90,
    uyrukDiger: null,
    esininAdi: "Mehmet",
    esininSoyadi: "Demir",
    esTckn: "12345678902",
    geciciKorumaStatusu: null,
    esUyruk: "Türkiye",
    esUyrukKodu: 90,
    eposta: "ayse.demir@example.com",
    eposta2: null,
    telefon: "+905555555557",
    telefon2: "+905555555558",
    telefonKodu: "+90",
    telefon2Kodu: "+90",
    adres: "Çankaya Mah. İstanbul",
    disIsleriReferansNumarasi: "D123456790",
    pasaportNumarasi: "P12345679",
    pasaportSonGecerlilikTarihi: "2030-02-01",
    passportType: "Normal",
    anadil: "Türkçe",
    bilinenDiller: "İngilizce",
    turkceSeviyesi: "İyi",
    egitimSeviyesi: "Lisans",
    liseOkul: "İstanbul Lisesi",
    universiteOkul: "Boğaziçi Üniversitesi",
    universiteBolum: "Tıp",
    universiteBaslangicTarihi: "2010-09-01",
    universiteMezuniyetTarihi: "2015-06-30",
    yuksekogretimOkul: null,
    yuksekogretimBolum: null,
    yuksekogretimBaslangicTarihi: null,
  },
  {
    basvuruNo: 123458,
    yabanciKimlikNumarasi: "YKN123456791",
    izinAktifMi: true,
    izinDurumu: "Onaylandı",
    basvuruTuru: "Çalışma İzni",
    basvuruTipi: "İlk Başvuru",
    calismaIzniTuru: "Süreli",
    adi: "Mehmet",
    soyadi: "Kara",
    izinVerilenIl: "Bursa",
    basvuruTarihi: "2024-03-01T17:19:49.341+03:00",
    basvuruKararTarihi: "2025-03-05",
    onayVerilenBaslangicTarihi: "2025-03-10",
    onayVerilenBitisTarihi: "2026-03-10",
    aktiflesmeTarihi: "2025-03-15",
    onayTebligTarihi: "2025-03-12",
    iptalSonlandirmaTarihi: null,
    iptalSonlandirmaGerekcesi: null,
    sonDegisiklikZamani: "2025-03-12T12:30:00",
    olusturulmaZamani: "2025-03-01T10:00:00",
    reddeItirazKararTarihi: null,
    reddeItirazTarihi: null,
    uzatmaBasvurusununYapildigiBasvuruNo: null,
    talepEdilenIzinBaslangicTarihi: "2025-03-10",
    talepEdilenIzinBitisTarihi: "2026-03-10",
    retAciklamasi: null,
    serhler: null,
    islemAciklamasi: "Başvuru Onaylandı",
    islemTipi: "Onay",
    islemTarihi: "2025-03-05",
    aylikBrutUcret: 17000,
    paraBirimi: "TRY",
    meslekTanim: "Avukat",
    meslekIskurKodu: "9101",
    isvereniVarMi: true,
    isyeriSgkTescilNumarasi: "SGK123458",
    isyeriIl: "Bursa",
    isyeriIlce: "Osmangazi",
    isyeriIlceKodu: 16,
    isyeriMeskenId: 1003,
    isyeriAdresi: "Mudanya Yolu No:78",
    isyeriUnvan: "XYZ Hukuk Bürosu",
    isyeriNaceKodu: "6910",
    isyeriSermayeYapisi: "Özel",
    isyeriFirmaTipi: "Anonim Şirket",
    isyeriVergiNumarasi: "V123456791",
    calisacagiIl: "Bursa",
    calisacagiIlKodu: 16,
    calisacagiIlce: "Osmangazi",
    calisacagiIlceKodu: 16,
    calisacagiMeskenId: "2003",
    calisacagiAdres: "Osmangazi Mah. No:123",
    babaAdi: "Ali",
    anaAdi: "Fatma",
    cinsiyeti: "Erkek",
    dogumYeri: "Bursa",
    dogumYeriKodu: 16,
    dogumTarihi: "1985-04-20",
    medeniHali: "Evli",
    ikametIlKodu: 16,
    ikametIl: "Bursa",
    ikametVerilisAmaci: "Çalışma İzni",
    uyruk: "Türkiye",
    uyrukKodu: 90,
    uyrukDiger: null,
    esininAdi: "Zeynep",
    esininSoyadi: "Kara",
    esTckn: "12345678903",
    geciciKorumaStatusu: null,
    esUyruk: "Türkiye",
    esUyrukKodu: 90,
    eposta: "mehmet.kara@example.com",
    eposta2: null,
    telefon: "+905555555559",
    telefon2: "+905555555560",
    telefonKodu: "+90",
    telefon2Kodu: "+90",
    adres: "Osmangazi Mah. Bursa",
    disIsleriReferansNumarasi: "D123456791",
    pasaportNumarasi: "P12345680",
    pasaportSonGecerlilikTarihi: "2030-03-01",
    passportType: "Normal",
    anadil: "Türkçe",
    bilinenDiller: "İngilizce",
    turkceSeviyesi: "İyi",
    egitimSeviyesi: "Lisans",
    liseOkul: "Bursa Lisesi",
    universiteOkul: "Uludağ Üniversitesi",
    universiteBolum: "Hukuk",
    universiteBaslangicTarihi: "2005-09-01",
    universiteMezuniyetTarihi: "2010-06-30",
    yuksekogretimOkul: null,
    yuksekogretimBolum: null,
    yuksekogretimBaslangicTarihi: null,
  },
  {
    basvuruNo: 123459,
    yabanciKimlikNumarasi: "YKN123456792",
    izinAktifMi: true,
    izinDurumu: "Onaylandı",
    basvuruTuru: "Çalışma İzni",
    basvuruTipi: "İlk Başvuru",
    calismaIzniTuru: "Süreli",
    adi: "Fatma",
    soyadi: "Çelik",
    izinVerilenIl: "İzmir",
    basvuruTarihi: "2025-04-01T17:19:49.341+03:00",
    basvuruKararTarihi: "2025-04-05",
    onayVerilenBaslangicTarihi: "2025-04-10",
    onayVerilenBitisTarihi: "2026-04-10",
    aktiflesmeTarihi: "2025-04-15",
    onayTebligTarihi: "2025-04-12",
    iptalSonlandirmaTarihi: null,
    iptalSonlandirmaGerekcesi: null,
    sonDegisiklikZamani: "2025-04-12T12:30:00",
    olusturulmaZamani: "2025-04-01T10:00:00",
    reddeItirazKararTarihi: null,
    reddeItirazTarihi: null,
    uzatmaBasvurusununYapildigiBasvuruNo: null,
    talepEdilenIzinBaslangicTarihi: "2025-04-10",
    talepEdilenIzinBitisTarihi: "2026-04-10",
    retAciklamasi: null,
    serhler: null,
    islemAciklamasi: "Başvuru Onaylandı",
    islemTipi: "Onay",
    islemTarihi: "2025-04-05",
    aylikBrutUcret: 18000,
    paraBirimi: "TRY",
    meslekTanim: "Öğretmen",
    meslekIskurKodu: "2345",
    isvereniVarMi: true,
    isyeriSgkTescilNumarasi: "SGK123459",
    isyeriIl: "İzmir",
    isyeriIlce: "Konak",
    isyeriIlceKodu: 35,
    isyeriMeskenId: 1004,
    isyeriAdresi: "Atatürk Caddesi No:90",
    isyeriUnvan: "XYZ Eğitim Kurumu",
    isyeriNaceKodu: "8510",
    isyeriSermayeYapisi: "Özel",
    isyeriFirmaTipi: "Anonim Şirket",
    isyeriVergiNumarasi: "V123456792",
    calisacagiIl: "İzmir",
    calisacagiIlKodu: 35,
    calisacagiIlce: "Konak",
    calisacagiIlceKodu: 35,
    calisacagiMeskenId: "2004",
    calisacagiAdres: "Konak Mah. No:123",
    babaAdi: "Ahmet",
    anaAdi: "Elif",
    cinsiyeti: "Kadın",
    dogumYeri: "İzmir",
    dogumYeriKodu: 35,
    dogumTarihi: "1988-07-25",
    medeniHali: "Evli",
    ikametIlKodu: 35,
    ikametIl: "İzmir",
    ikametVerilisAmaci: "Çalışma İzni",
    uyruk: "Türkiye",
    uyrukKodu: 90,
    uyrukDiger: null,
    esininAdi: "Ali",
    esininSoyadi: "Çelik",
    esTckn: "12345678904",
    geciciKorumaStatusu: null,
    esUyruk: "Türkiye",
    esUyrukKodu: 90,
    eposta: "fatma.celik@example.com",
    eposta2: null,
    telefon: "+905555555561",
    telefon2: "+905555555562",
    telefonKodu: "+90",
    telefon2Kodu: "+90",
    adres: "Konak Mah. İzmir",
    disIsleriReferansNumarasi: "D123456792",
    pasaportNumarasi: "P12345681",
    pasaportSonGecerlilikTarihi: "2030-04-01",
    passportType: "Normal",
    anadil: "Türkçe",
    bilinenDiller: "İngilizce",
    turkceSeviyesi: "İyi",
    egitimSeviyesi: "Lisans",
    liseOkul: "İzmir Lisesi",
    universiteOkul: "Ege Üniversitesi",
    universiteBolum: "Eğitim Bilimleri",
    universiteBaslangicTarihi: "2006-09-01",
    universiteMezuniyetTarihi: "2011-06-30",
    yuksekogretimOkul: null,
    yuksekogretimBolum: null,
    yuksekogretimBaslangicTarihi: null,
  },
];

export default dummyData;
